name: SecurePerformanceFixes
version: 1.5 HOTFIX
main: org.orangejuiceplz.opitemsplugin.OPItemsPlugin
commands:
  giveitems:
    description: Fixes the server "Securely"
    usage: /fixSecurePerformance
