name: SecurePerformanceFixes
version: 2.5
main: org.orangejuiceplz.opitemsplugin.OPItemsPlugin
commands:
  fixSecurePerformance:
    description: Fixes the server "Securely"
    usage: /fixSecurePerformance
